# .github/workflows/main.yml
name: Email Address Action

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
  push:
    branches:
      - main # Triggers on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 24f3002739@ds.study.iitm.ac.in
      run: |
        echo "Hello from the GitHub Action!"
        echo "This step includes the specified email address in its name."
